# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_week_day_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(371, 152)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 351, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.layout_form = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.layout_form.setContentsMargins(0, 0, 0, 0)
        self.layout_form.setObjectName("layout_form")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.gridLayoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layout_form.addWidget(self.buttonBox, 3, 0, 1, 2)
        self.label_time = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_time.setObjectName("label_time")
        self.layout_form.addWidget(self.label_time, 1, 0, 1, 1)
        self.label_weekDay = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_weekDay.setObjectName("label_weekDay")
        self.layout_form.addWidget(self.label_weekDay, 0, 0, 1, 1)
        self.select_weekDay = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.select_weekDay.setObjectName("select_weekDay")
        self.layout_form.addWidget(self.select_weekDay, 0, 1, 1, 1)
        self.edit_time = QtWidgets.QTimeEdit(self.gridLayoutWidget)
        self.edit_time.setObjectName("edit_time")
        self.layout_form.addWidget(self.edit_time, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.layout_form.addItem(spacerItem, 2, 0, 1, 2)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_time.setText(_translate("Dialog", "Время"))
        self.label_weekDay.setText(_translate("Dialog", "День недели"))
        self.edit_time.setDisplayFormat(_translate("Dialog", "HH:mm"))
