# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'warning_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 160)
        self.label_warning = QtWidgets.QLabel(Dialog)
        self.label_warning.setGeometry(QtCore.QRect(16, 24, 360, 64))
        self.label_warning.setText("")
        self.label_warning.setAlignment(QtCore.Qt.AlignCenter)
        self.label_warning.setObjectName("label_warning")
        self.btn_yes = QtWidgets.QPushButton(Dialog)
        self.btn_yes.setGeometry(QtCore.QRect(190, 110, 93, 28))
        self.btn_yes.setObjectName("btn_yes")
        self.btn_no = QtWidgets.QPushButton(Dialog)
        self.btn_no.setGeometry(QtCore.QRect(300, 110, 93, 28))
        self.btn_no.setObjectName("btn_no")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_yes.setText(_translate("Dialog", "Да"))
        self.btn_no.setText(_translate("Dialog", "Нет"))
